[package]
name = "AsynchronousChatServer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
env_logger = "0.11.6"
log = "0.4"
clap = { version = "4.0" }
chrono = "0.4"
